<?php
	$callbackSuffixes = array(
			'Behance' => 'oauth2_callback',
			'Bitbucket' => 'oauth_callback',
			'Bitly' => 'oauth_callback',
			'Disqus' => 'oauth2callback',
			'Do' => 'oauth2callback',
			'Evernote' => 'oauth_callback',
			'Facebook' => 'int_callback',
			'Flickr' => 'oauth_callback',
			'Foursquare' => 'int_callback',
			'GitHub' => 'oauth2callback',
			'Google' => 'oauth2callback',
			'Instagram' => 'int_callback',
			'LinkedIn' => 'oauth2callback',
			'Live' => 'oauth2callback',
			'Mixi' => 'oauth2callback',
			'Paypal' => 'int_callback',
			'SinaWeibo' => 'sina_callback',
			'Twitter' => 'oauth_callback',
			'Vimeo' => 'oauth_callback',
			'VKontakte' => 'int_callback',
                        'Yahoojp' => 'oauth2callback',
                        'LoginCidadao' => 'oauth2_callback',
	);
?>
